# Generated by Django 4.0.3 on 2022-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
