# Generated by Django 4.0.3 on 2022-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosAPI', '0002_alter_venta_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
    ]
