# Generated by Django 4.0.3 on 2022-08-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosAPI', '0003_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='costo_de_inventario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='deficit_de_productos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='estado_de_cuenta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
