# Generated by Django 4.0.3 on 2022-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosAPI', '0004_reporte_costo_de_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='ventas',
            field=models.ManyToManyField(blank=True, null=True, to='repuestosAPI.venta'),
        ),
    ]
